import java.util.*;
class ExceptionDemo3
{
    public static void main(String a[])
    {
        String s1 = "Marvellous";
        string s2 = null;

        System.out.println("data of is: "+s1);
        System.out.println("data of is: "+s2);

       // these are three problems we generated
       //it is handled by exception handling
       //null pointer exception
       //divide by 0
       // array index out of 
        System.out.println("length of s1 is: "+s1.length());
        System.out.println("length of s2 is: "+s2.length());


    }
}